import { copyFile, mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

const copies = [
  ["node_modules/sweetalert2/dist/sweetalert2.all.min.js", "public/vendor/sweetalert2/sweetalert2.all.min.js"],
  ["node_modules/chart.js/dist/chart.umd.js", "public/vendor/chart.js/chart.umd.js"],
  ["node_modules/chart.js/LICENSE.md", "public/vendor/chart.js/LICENSE.md"],
  ["node_modules/sortablejs/Sortable.min.js", "public/vendor/sortablejs/Sortable.min.js"],
  ["node_modules/sortablejs/LICENSE", "public/vendor/sortablejs/LICENSE"],
];

const fontFamilies = {
  inter: { label: "Inter", weights: [300, 400, 500, 600, 700] },
  poppins: { label: "Poppins", weights: [300, 400, 500, 600, 700] },
  "plus-jakarta-sans": { label: "Plus Jakarta Sans", weights: [300, 400, 500, 600, 700] },
  manrope: { label: "Manrope", weights: [400, 500, 600, 700, 800] },
};

for (const [source, destination] of copies) {
  const target = join(root, destination);
  await mkdir(dirname(target), { recursive: true });
  await copyFile(join(root, source), target);
}

const sweetAlertLicense = await readFile(join(root, "node_modules/sweetalert2/LICENSE"), "utf8");
await writeFile(
  join(root, "public/vendor/sweetalert2/LICENSE"),
  `${sweetAlertLicense.trimEnd()}\n`,
  "utf8",
);

let fontsCss = "/* Generated by scripts/build-assets.mjs. */\n";
for (const [family, config] of Object.entries(fontFamilies)) {
  await mkdir(join(root, "public/fonts/licenses"), { recursive: true });
  await copyFile(
    join(root, "node_modules", `@fontsource/${family}`, "LICENSE"),
    join(root, "public/fonts/licenses", `${family}.txt`),
  );

  for (const weight of config.weights) {
    const filename = `${family}-latin-${weight}-normal.woff2`;
    const source = join(root, "node_modules", `@fontsource/${family}`, "files", filename);
    const destination = join(root, "public/fonts", filename);
    await mkdir(dirname(destination), { recursive: true });
    await copyFile(source, destination);
    fontsCss += `@font-face { font-family: '${config.label}'; font-style: normal; font-display: swap; font-weight: ${weight}; src: url('/fonts/${filename}') format('woff2'); }\n`;
  }
}

await writeFile(join(root, "public/css/fonts.css"), fontsCss, "utf8");
